name: E-commerce Platform

on:
  push:
    branches:
      - master
     
jobs:
  build-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Use the correct AWS region code for Mumbai

      - name: Deploy Static Site
        run: aws s3 sync . s3://shresty-github --delete --exclude ".git/*"
